[package]
name = "testdebug"
version = "0.1.0"
authors = ["Me"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.6.2"
